services:
  # Service Registry (Eureka)
  registry-discovery:
    container_name: id-eureka
    image: payment/microservice-docker-eurekaserver:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -Dspring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    networks:
      - app-network

  # Configuration Service
  configuration:
    container_name: id-config
    image: payment/microservice-docker-configserver:0.0.1-SNAPSHOT
    volumes:
      - ./config-server-repo:/tmp/config-server-repo
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
    depends_on:
      - registry-discovery
    ports:
      - "8888:8888"
    networks:
      - app-network


  # SpringBootAdmin
  springbootadmin:
    container_name: id-springbootadmin
    image: payment/microservice-docker-springbootadmin:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
    depends_on:
      - registry-discovery
    ports:
      - "8762:8762"
    networks:
      - app-network

  # API Gateway Service
  apigateway:
    container_name: id-apigateway
    image: payment/microservice-docker-apigateway:1.0-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
        -Dspring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    depends_on:
      - registry-discovery
      - configuration
    ports:
      - "8080:8080"
    networks:
      - app-network

  # Product Service
  product-catalog:
    container_name: bd-product-catalog
    image: payment/microservice-docker-product:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
    depends_on:
      - registry-discovery
      - configuration
    ports:
      - "8083:8083"
    networks:
      - app-network

  # Customer Service
  customer:
    container_name: bd-customer
    image: payment/microservice-docker-customer:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
    depends_on:
      - registry-discovery
      - configuration
    ports:
      - "8081:8080"
    networks:
      - app-network

  # Transaction Service
  transactions:
    container_name: bd-transactions
    image: payment/microservice-docker-transaction:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
    depends_on:
      - registry-discovery
      - configuration
    ports:
      - "8082:8082"
    networks:
      - app-network

  # PostgreSQL Database Service
  postgres:
    container_name: postgres_db
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dbfiles:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
    networks:
      - app-network

  # PgAdmin Service
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_gui
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "qwerty"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network

  # Keycloak Server
  keycloak:
    container_name: id-keycloak
    image: quay.io/keycloak/keycloak:22.0.5
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
    command: start-dev
    ports:
      - "8091:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
