server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: customer_full
          uri: lb://businessdomain-customer
          predicates:
            - Path=/customer/full/**
          filters:
            - name: AuthenticationFiltering

        - id: customer_service
          uri: lb://businessdomain-customer
          predicates:
            - Path=/customer/**

        - id: transactionService
          # âœ… CORREGIDO: businessdomain-transaction (SINGULAR)
          uri: lb://businessdomain-transaction
          predicates:
            - Path=/transaction/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: AuthenticationFiltering